### PR TITLE
Add a new layout: 8th centered

### PR DESCRIPTION
**Pull request by abique**
This layout is useful because you have the root key in "center left", down fifth in the left and up fifth in the right.

### CODE REVIEW

**Comment by teotigraphix** [comment]
Ha, I was just going to say we don't use tabs, then your last commit. :)

**Comment by abique** [comment]
Yes sorry, I fixed the style issues.

**Comment by abique** [comment]
By the way I thought that it could be interesting to highlight the fifth, or have an option to do so

**Comment by teotigraphix** [comment]
I don't see any reason I can't merge this so I will.

**Comment by abique** [comment]
Thank you :+1:

**Pull request merged**
